export { default as Navbar } from "../Components/Navbar/Navbar";
export { default as Hero } from "../Components/Hero/Hero";
export { default as Card } from "../Components/Card/Card";
export { default as NameBar } from "../Components/NameBar/NameBar";
export { default as Search } from "../Components/Search/Search";
export { default as Footer } from "../Components/Footer/Footer";
export { default as Spinner } from "../Components/Spinner/Spinner";
export { default as CountryModal } from "../Components/CountryModal/CountryModal";
export { default as Paginate } from "../Components/Paginate/Paginate";
